config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  delete "/:phrase/passwords/:id/:route/" => "passwords#destroy", as: "destroy_password"

  get "/:phrase" => "passwordmanager#home"

  post "/:phrase/passwordmanager/search" => "passwordmanager#search", as:"passwordmanager_search"

  post "/:phrase/passwordmanager/order" => "passwordmanager#order", as: "passwordmanager_order"

  post "/:phrase/passwordmanager/getallpasswords" => "passwordmanager#getAllPasswords", as: "get_all_passwords_passwordmanager"

  get "/:phrase/passwordmanager/:login/show" => "passwordmanager#showLogin", as: "passwordmanager_showLogin"

  get "/:phrase/passwordmanager/editphrase" => "passwordmanager#editphrase", as:"edit_phrase_passwordmanager"

  patch "/:phrase/passwords/updateAllPasswd" => "passwords#updateAllPassw", as: "update_all_passwd_passwords"

  scope "/:phrase/" do 
    resources :passwordmanager, :passwords
  end

 root to: "passwordmanager#home"

end

app/models/password.rb
class Password < ActiveRecord::Base
	belongs_to :user

	validates :login, presence: true
	validates :url, presence: true
	validates :password, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :passwords

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  helper_method :passwdURLHelper, :passwdURLMethodHelper
end

app/controllers/passwordmanager_controller.rb
class PasswordmanagerController < ApplicationController
	def index

		unless params[:phrase]
			redirect_to"/"
		end

		@bookmark = 2;
		@phrase = params[:phrase]

		@passwords = searchString

		@route = "index"

	end

	def search
		session[:search_string] = params[:term]
		session[:search_where] = params[:search_id]

		@passwords = searchString
	end

	def showLogin
		@password = Password.where "login = ? AND user_id = ?",htmlSpecialCharsReverseHp(params[:login]),current_user.id
		@password = @password.order("LOWER(url) ASC")
		@route = "showLogin"
	end

	def new
		@password = Password.new
	end

	def edit
		begin
			@password = Password.find(params[:id])
			unless @password.user_id == current_user.id
				flash[:alert] = "Die angegebene ID gehört nicht zu diesem Account"
				redirect_to passwordmanager_index_url
			end
		rescue Exception => e
			flash[:alert] = "Die angegebene ID konnte nicht gefunden werden"
			redirect_to passwordmanager_index_url
		end
	end

	def home
		if params[:phrase]
			redirect_to passwordmanager_index_path(params[:phrase])
		end
	end

	def order
		session[:order_by] = params[:orderID]
		@passwords = searchString
	end

	def editphrase

	end

	def getAllPasswords
		@passwords = Password.all
	end

	private
		def searchString
			unless(session[:search_string] == "")
				case(session[:search_where])
					when "2"
						@password = Password.where "user_id = ? AND login LIKE ? ","#{current_user.id}","%#{session[:search_string]}%"
					when "3"
						@password = Password.where "user_id = ? AND url LIKE ?","#{current_user.id}","%#{session[:search_string]}%"
					else
						@password = Password.where "user_id = ? AND login LIKE ? OR url LIKE ?","#{current_user.id}","%#{session[:search_string]}%","%#{session[:search_string]}%"
				end	
			else
				@password = Password.where "user_id = ? ","#{current_user.id}"
			end

			case(session[:order_by])
				when "1"
					@password = @password.order('LOWER(login) ASC, LOWER(url) ASC')
				when "2"
					@password = @password.order('LOWER(login) DESC, LOWER(url) DESC')
				when "3"
					@password = @password.order('LOWER(url) ASC, LOWER(login) ASC')
				when "4"
					@password = @password.order('LOWER(url) DESC, LOWER(login) DESC')
				else
					@password = @password.order('LOWER(login) ASC, LOWER(passwordmanager_index_url) ASC')
			end

			return @password
		end

		def htmlSpecialCharsReverseHp sentence
			sentence = sentence.gsub '&#64;', '@'
			sentence = sentence.gsub '&#47;','/'
			return sentence.gsub '&#46;','.'
		end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
	def edit
		@password = Password.find(params[:id])
	end

	def create
		phrase = params[:password].delete(:phrase)
		@passParams = password_params

		@password = Password.new @passParams

		if(@password.save)
			current_user.passwords << @password
			flash[:notice] = "'#{@password.url}' wurder erfolgreich erstellt!"
			redirect_to passwordmanager_index_path(phrase)
		else
			redirect_to new_passwordmanager_path(phrase)
		end
	end

	def update
		phrase = params[:password].delete(:phrase)
		@passwd = Password.find(params[:id])
		@passParams = password_params

		if(@passParams[:password] == "")
			@passParams.delete(:password)
		end
		
		if @passwd.update_attributes(@passParams)
			flash[:notice] = "'#{@passwd.url}' wurde erfolgreich verändert!"
			redirect_to passwordmanager_index_path(phrase)
		else
			redirect_to edit_passwordmanager_path(phrase,params[:id])
		end
	end

	def destroy
		@passwd = Password.find(params[:id])
		@url = @passwd.url
		@passwd.destroy
		flash[:notice] = "'#{@url}' wurde erfolgreich gelöscht"

		@passwordsInDataB = Password.where "login = ?","#{@passwd.login}"

		case(@passwordsInDataB.count)
			when 0
				redirect_to passwordmanager_index_path(params[:phrase])
			else
				case(params[:route])
					when "index"
						redirect_to passwordmanager_index_path(params[:phrase])
					when "showLogin"
						redirect_to passwordmanager_showLogin_path(params[:phrase],@passwd.login)
					else
						redirect_to passwordmanager_index_path(params[:phrase])
				end
		end
	end

	def updateAllPassw
		@passwd = Password.find(params[:pwUpdateID])
		@params2 = {:password => params[:pwUpdatePw]}

		if(@passwd.update_attributes(@params2))
			puts "erfolgreich"
		else
			puts "nicht erfolgreich"
		end
	end

	private
		def password_params
			params.require('password').permit("url", "login", "password")
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def passwdURL password
		if password.new_record?
			return passwords_path(phrase: params[:phrase])
		else
			return password_path(@password,phrase: params[:phrase])
		end
	end

	def passwdURLMethod password
		if password.new_record?
			return :post
		else
			return :patch
		end
	end

	def htmlSpecialCharsHp sentence
		sentence = sentence.gsub '@', '&#64;'
		sentence = sentence.gsub '/','&#47;'
		return sentence.gsub '.','&#46;'
	end

	def htmlSpecialCharsReverseHp sentence
		sentence = sentence.gsub '&#64;', '@'
		sentence = sentence.gsub '&#47;','/'
		return sentence.gsub '&#46;','.'
	end
end

app/helpers/passwordmanager_helper.rb
module PasswordmanagerHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Passwortmanager</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application' %>
	<%= csrf_meta_tags %>
</head>
<body>
	<% if session[:order_by] == nil %>
		<% session[:order_by] = "1" %>
	<% end %>
	<table border="0" cellspacing="10" cellpadding="0" width="100%">
		<tr>
			<td><div id="divUeber">Passwort Manager</div></td>
		</tr>
		<tr>
			<td>&#160;</td>
		</tr>

		<% if flash[:alert] %>
			<tr>
				<td >
					<div class="error"><%= flash[:alert] %></div>
				</td>
			</tr>
		<% end %>

		<% if flash[:notice] %>
			<tr>
				<td >
					<div class="notice"><%= flash[:notice] %></div>
				</td>
			</tr>
		<% end %>
		
		<tr>
			<td><%= yield %></td>
		</tr>
	</table>
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Passwordmanager</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>

	<div id="divUeber">Passwort Manager</div>
	<div id="divDeviseContent">
		<div id="divDCLinks">
				<%= render "devise/shared/links" %>
		</div>
		
		<div id="divDCContent">
			<table border="0" cellpadding="0" cellspacing="0" width="100%">
				<% if flash[:alert] %>
					<tr>
						<td >
							<div class="error"><%= flash[:alert] %></div>
						</td>
					</tr>
				<% end %>

				<% if flash[:notice] %>
					<tr>
						<td >
							<div class="notice"><%= flash[:notice] %></div>
						</td>
					</tr>
				<% end %>

				<tr>
					<td><%= yield %></td>
				</tr>
			</table>
		</div>
	</div>

</body>
</html>

app/views/passwordmanager/_bar.html.erb
<div id="divLeiste">
	<table border="0" cellspacing="5" cellpadding="0" 
		<% unless params[:action] == "home" %>
			style="margin-top:-9px;"
		<% end %>
	>
		<tr>
			<td>Angemeldet als:</td>
			<td id="tdUserEmail"><%= link_to current_user.email, edit_user_registration_url, :email => current_user.email, :id => "aEmail" %></td>
			<td> | </td>
			<% if params[:phrase] %>
				<td><%= link_to "Phrase bearbeiten", edit_phrase_passwordmanager_url %></td>
				<td> | </td>
			<% end %>
			<td><%= link_to "Abmelden", destroy_user_session_url, method: :delete %></td>
			<td><div id="divUserLastSignIn"><%= current_user.current_sign_in_at %></div></td>
			<td><div id="divUserPhrase"><%= params[:phrase] %></div></td>
			<td width="10%">&#160;</td>
			<td>
				<%- if params[:phrase] %>
					<div id="divNavigation">
						<%= render "passwordmanager/navigation" %>
					</div>
				<% end -%>
			</td>
		</tr>
	</table>
</div>

app/views/passwordmanager/_form.html.erb
<div id="divEdNew">
	<table border="0" cellspacing="10" cellpadding="0" width="100%">
	<tr>
		<td>
			<div class="error">
				<ul>
				<% @password.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
				</ul>
			</div>
		</td>
	</tr>
	<tr>		
		<%= form_for(@password, url: passwdURL(@password),method: passwdURLMethod(@password)) do |p| %>
			<%= p.hidden_field "phrase",  value: params[:phrase] %>
			<table border="1" cellspacing="0" cellpadding="10">
				<tr>
					<td><%= p.label :url %></td>
					<td><%= p.text_field :url %></td>
				</tr>
				<tr>
					<td><%= p.label :login %></td>
					<td><%= p.text_field :login %></td>
				</tr>
				<tr> 	
					<td><%= p.label :password ,"Passwort" %></td>
					<td><%= p.password_field :password , :id => "inpEdNePasswd", :onkeyup => "changePassw();" %></td>
				</tr>
				<tr>
					<td style="text-align:center;"><input type="checkbox" id="cbEdNePlaintext" onchange="showPlainText()" /></td>
					<td>Passwort anzeigen</td>
				</tr>
				<tr>
					<td colspan="2" style="text-align:center;"><button id="btVerschluesseln" type="button" onclick="btClickVerschl()">Verschlüsseln</button></td>
				</tr>
				<tr>
					<% if @password.new_record? %>
						<td colspan="2" style="text-align: center;"><%= p.submit "Senden", :disabled => 'disabled',:id => 'btEdNeSenden' %></td>
					<% else %>
						<td colspan="2" style="text-align: center;"><%= p.submit "Senden",:id => 'btEdNeSenden' %></td>
					<% end %>
				</tr>
				<% end %>
			</table>
		</td>
	</tr>
</div>

app/views/passwordmanager/_getAllPasswords.html.erb
<% passwords.each do |passwd| %>
	<%= "<div>#{passwd.id}</div><div>#{passwd.password}</div>" %>
<% end %>

app/views/passwordmanager/_navigation.html.erb
<table border="0" cellspacing="10" cellpadding="0" width="100%">
	<tr>
		<td><%= link_to "Home", passwordmanager_index_url %></td>
		<td> | </td>
		<td><%= link_to "Neues Passwort", new_passwordmanager_url %></td>
		<td> | </td>
		<td><a class="clickAble" onclick="location.href = '/';">Phrase erneut eingeben</a></td>
	</tr>
</table>

app/views/passwordmanager/_searchBar.html.erb
<div id="searchBar">
	<%= form_tag passwordmanager_search_url,:id => "seachSubmit",remote: true do %>
		<table border="0" cellspacing="10" cellpadding="0" width="100%">
			<tr>
				<td width="10%">
					<div class="tableLoginTdMiddle">
						Suche: 
					</div>
				</td></td>
				<td width="20%">
					<%= select_tag(:search_id, options_for_select([['All', 1], ['Email', 2], ['URL', 3]], session[:search_where]),:onchange => "$('#seachSubmit').submit();") %>
				</td>
				<td width="70%"><%= text_field_tag :term ,"",:onkeyup => "$('#seachSubmit').submit(); ",:value => "#{session[:search_string]}" %></td>
			</tr>
		</table>
	<% end %>
</div>

app/views/passwordmanager/_search_body.html.erb
<% i = 0 %>
<% passwords.each do |passwd| %>
	<% i += 1 %>
	<% @login = passwd.login.gsub '@','&#64;' %>
	<div class="divIPassword">
		<table border="0" cellspacing="10" cellpadding="0" width="100%">
			<tr>
				<td width="5%"><%= i %>.</td>
				<% if isLogin %>
					<td width="20%"><%= link_to passwd.login,passwordmanager_showLogin_path(params[:phrase],htmlSpecialCharsHp(passwd.login)) %></td>
				<% end %>
				<td width="20%"><%= passwd.url %></td>
				<td width="20%">
					<div id=<%= "divPasswdUeber#{passwd.id}" %> password=>********************</div>
					<div style="display:none;" id=<%= "divPasswdUeber#{passwd.id}passwd" %>><%= passwd.password %></div>
				</td>
				<td width="15%" ><div id=<%= "tdPasswdTimer#{passwd.id}" %>>
					<a class="divPasswdUeber" passwordID=<%= "#{passwd.id}" %>>Passwort anzeigen</a>
				</div></td>
				<td width="10%"><%= link_to "bearbeiten", edit_passwordmanager_path(params[:phrase],passwd) %></td>
				<td width="10%"><%= link_to 'löschen', destroy_password_path(params[:phrase],passwd,route), data: {confirm: "'#{passwd.url}' wirklich löschen?"}, method: :delete %></td>
			</tr>
		</table>
	</div>
<% end %>

app/views/passwordmanager/_search_body_top.html.erb
<div class="divIPassword">
	<div id="orderList"><%= session[:order_by] %></div>

	<%= form_tag passwordmanager_order_url, :id => "orderSubmit",remote: true do %>
		<%= hidden_field_tag "orderID",session[:order_by] %>
	<% end %>

	<table border="0" cellspacing="10" cellpadding="0" width="100%">
		<tr>
			<td width="5%"></td>
			<% if isLogin %>
				<td width="20%" valign="top">
					<div>
						<table border="0" cellspacing="0" cellpadding="0"  style="margin-top:-7px;">
							<tr>
								<td><div>Login:</div></td>
								<td>
									<table border="0" cellspacing="0" cellpadding="0" style="margin-top:-10px;">
										<tr>
											<td>
												<div class="clickAble" id="loginASC" style="margin-left:20px;" onclick="reorderList('loginASC');">
													<% if session[:order_by] == "1" %>
															<%= image_tag("cornerUpActive.png",:width => "15px") %>
													<% else %>
															<%= image_tag("cornerUp.png",:width => "15px") %>
													<% end %>
												</div>
											</td>
										</tr>
										<tr>
											<td>
												<div class="clickAble" id="loginDESC" style="margin-left:20px;" onclick="reorderList('loginDESC');">
													<% if session[:order_by] == "2" %>
														<%= image_tag("cornerDownActive.png",:width => "15px") %>
													<% else %>
														<%= image_tag("cornerDown.png",:width => "15px") %>
													<% end %>
												</div>
											</td>
										</tr>
									</table>
								</td>
							</tr>
						</table>
					</div>
				</td>
			<% end %>
			<td width="20%" valign="top">
				<div>
						<table border="0" cellspacing="0" cellpadding="0"  style="margin-top:-7px;">
							<tr>
								<td><div>URL:</div></td>
								<td>
									<% if isLogin %>
										<table border="0" cellspacing="0" cellpadding="0" style="margin-top:-10px;">
											<tr>
												<td>
													<div class="clickAble" id="" style="margin-left:20px;" onclick="reorderList('urlASC');">
														<% if session[:order_by] == "3" %>
																<%= image_tag("cornerUpActive.png",:width => "15px") %>
														<% else %>
																<%= image_tag("cornerUp.png",:width => "15px") %>
														<% end %>
													</div>
												</td>
											</tr>
											<tr>
												<td>
													<div class="clickAble" style="margin-left:20px;" onclick="reorderList('urlDESC');">
														<% if session[:order_by] == "4" %>
															<%= image_tag("cornerDownActive.png",:width => "15px") %>
														<% else %>
															<%= image_tag("cornerDown.png",:width => "15px") %>
														<% end %>
													</div>
												</td>
											</tr>
										</table>
									<% end %>
								</td>
							</tr>
						</table>
					</div>
			</td>
			<td width="20%" valign="top"><div style="margin-top:-3px;">Passwort:</div></td>
			<td width="15%" valign="top"></td>
			<td width="10%"></td>
			<td width="10%"></td>
		</tr>
	</table>
</div>

app/views/passwordmanager/edit.html.erb
<table border="0" cellspacing="10" cellpadding="0" width="100%" height="100%" style="min-width:1200px;">
	<tr>
		<td><%= render "passwordmanager/bar" %></td>
	</tr>
	<tr>
		<td><%= render "passwordmanager/form" %></td>
	</tr>
</table>

app/views/passwordmanager/editphrase.html.erb
<table border="0" cellpadding="0" cellspacing="10" width="100%">
	<div style="display:none;" id="divEdPhrLager"></div>
	<%= form_tag get_all_passwords_passwordmanager_url, :id => "subGetAllPasswords", remote: true do %>
		<%= hidden_field_tag "orderID" %>
	<% end %>

	<%= form_tag update_all_passwd_passwords_url,:id => "subUpdateAllPasswords",method: :patch,remote:true do %>
		<%= hidden_field_tag "pwUpdateID" %>
		<%= hidden_field_tag "pwUpdatePw" %>
	<% end %>

	<tr>
		<td><%= render partial: "passwordmanager/bar" %></td>
	</tr>
	<tr>
		<td>
			<div id="divEditPhrase">
				<table border="0" cellspacing="0" cellpadding="10" width="100%">
					<tr>
						<td colspan="2"><div id="divEdPhError" class="error"></div></td>
					</tr>
					<tr>
						<td colspan="2"><div id="divEdPhErfolg" class="notice"></div></td>
					</tr>
					<tr>
						<td colspan="2">
							<div class="tableLoginTdMiddle"><u>Phrase bearbeiten:</u></div>
						</td>
					</tr>
					<tr>
						<td colspan="2">
							<div class="error">
								Bitte merken Sie sich die neue Phrase sehr gut!<br />
								Sie kann <u><strong>NICHT</strong></u> wiederhergestellt werden!<br />
							</div>
						</td>
					</tr>
					<tr>
						<td class="tableLoginTdLabel" width="30%">alte Phrase:</td>
						<td width="65%">
							<input type="password" id="inpOldPasswd" class="inpPhrEd" style="width:95%;" />
						</td>
					</tr>	
					<tr>
						<td class="tableLoginTdLabel" width="30%">neue Phrase:</td>
						<td width="65%">
							<input type="password" id="inpEPPasswd" class="inpPhrEd" style="width:95%;" />
						</td>
					</tr>	
					<tr>
						<td class="tableLoginTdLabel" width="30%">neue Phrase wdh.:</td>
						<td width="65%">
							<input type="password"  id="inpEPPasswdWhd" class="inpPhrEd" style="width:95%;" />
						</td>
					</tr>
					<tr>
						<td>
							<div class="tableLoginTdLabel">
								<input type="checkbox" id="cbEditPhrase" onchange="epPhrasePlainText();" />
							</div>
						</td>
						<td>Phrasen anzeigen</td>
					</tr>	
					<tr>
						<td></td>
						<td>
							<button type="button" id="btEPSenden" onclick="btEditPhrase();">Ändern</button>
						</td>
					</tr>			
				</table>
			</div>
		</td>
	</tr>
</table>

app/views/passwordmanager/home.html.erb
<%= render "passwordmanager/bar" %>

<div id="divPhrase">
	<table border="0" cellspacing="10" cellpadding="0">
		<tr>
			<td colspan="2">
				<div class="tableLoginTdMiddle" id="divPhraseUeber">
					Phrase
				</div>
			</td>
		</tr>

		<tr>
			<td colspan="2">
				<div class="tableLoginTdMiddle" style="color:red;">
					Bitte merken Sie sich die Phrase gut!<br />
					Sie wird zum ver- / entschlüsseln der Passwörter gebraucht und kann <u><strong>NICHT</strong></u> wiederhergestellt werden!<br/><br />
					Falls das Passwort <strong>NICHT</strong> entschlüsselt wurde, ist die eingegebene Phrase falsch!
				</div>
			</td>
		</tr>

		<tr>
			<td>Phrase: </td>
			<td><input type="password" id="inpPhrase" onkeyup="sendPhraseInput(event);" autofocus /></td>
		</tr>

		<tr>
			<td>
				<div class="tableLoginTdMiddle">
					<input type="checkbox" id="cbPhransePlainText" onchange="plainPassword();" />
				</div>
			</td>
			<td>Phrase anzeigen</td>
		</tr>

		<tr>
			<td></td>
			<td><button id="btPhraseSend" type="button" onclick="sendPhrase();">Send</button></td>
		</tr>
	</table>
</div>

app/views/passwordmanager/index.html.erb
<table border="0" cellspacing="10" cellpadding="0" width="100%" height="100%" style="min-width:1200px;">
	<tr>
		<td><%= render "passwordmanager/bar" %></td>
	</tr>
	<tr>
		<td><%= render "passwordmanager/searchBar" %></td>
	</tr>

	<tr>
		<td>
			<table border="0" cellspacing="0" cellpadding="0" width="100%">
				<tr>
					<td>
						<div id="divIndexBar">
							<%= render partial: 'passwordmanager/search_body_top', locals: {isLogin: true} %>
						</div>
					</td>
				</tr>
				<tr>
					<td>
						<div id="divIndexInhalt">
							 <%= render partial: 'passwordmanager/search_body', locals: {passwords:@passwords,isLogin: true,route: @route} %>
						</div>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

app/views/passwordmanager/new.html.erb
<table border="0" cellspacing="10" cellpadding="0" width="100%" height="100%" style="min-width:1200px;">
	<tr>
		<td><%= render "passwordmanager/bar" %></td>
	</tr>
	<tr>
		<td><%= render "passwordmanager/form" %></td>
	</tr>
</table>

app/views/passwordmanager/showLogin.html.erb
<table border="0" cellspacing="10" cellpadding="0" width="100%">
	<tr>
		<td><%= render partial: "passwordmanager/bar" %></td>
	</tr>
	<tr><td>&#160;</td></tr>
	<tr>
		<td>
			<div id="divSLUeber">
				<%= "Addressen mit '#{htmlSpecialCharsReverseHp(params[:login])}' als login:" %>
			</div>
		</td>
	</tr>
	<tr>
		<td>
			<table border="0" cellspacing="0" cellpadding="0" width="70%" style="margin-left:20%;">
				<tr>
					<td>
						<%= render partial: 'passwordmanager/search_body_top', locals: {isLogin: false} %>
						</td>
					<tr>
						<td>
							<div>
								<%= render partial: "passwordmanager/search_body", locals: {passwords: @password,isLogin: false,route: @route} %>
							</div>
						</td>
					</tr>
				</tr>
			</table>
		</td>
	</tr>
</table>

app/views/passwordmanager/test.html.erb
test12